version: "3.8"
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=secret
      - MONGO_USER=gynflo
      - MONGO_PASSWORD=mypassword
    command: node index.js

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gynflo
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
 
