version: "3.8"
services:
  node-app:
    build: .
    image: gynflo/node_app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
